In [10]:
import numpy as np

In [11]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [12]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [13]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [14]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [15]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

In [16]:
np.array([
	[1,2],
	[3,4]
]).dot([1,1])

array([3, 7])

In [20]:
tens = np.arange(1,11)
ones = np.ones(shape=10)

tens+ones

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [23]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])